import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const inter = localFont({
  src: '../public/fonts/Inter.ttf',
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased bg-(--neutral-50)`}
    >
      <body className="h-dvh flex flex-col p-4">{children}</body>
    </html>
  );
}
